### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Tera-Scripts** [Midoriykawa/fishmaster#1]
stop scamming people, and editing my message

**Comment by Midoriykawa** [comment]
u dont buy script:D stfu scamer' all work

**Comment by Tera-Scripts** [comment]
You are sad

**Comment by Midoriykawa** [comment]
l2p kid cry more

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.
